/* 
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Other/SQLTemplate.sql to edit this template
 */
/**
 * Author:  hchri
 * Created: 29 feb 2024
 */
# CONSULTA CON UNA CONDICION 
# METODO WHERE
SELECT * FROM USUARIOS WHERE EMAIL = "hchristianandres@gmail.com";

/*EXISTE METODOS DE COMPARACIÓN
    IGUAL =
    DISTINTO !=
    MENOR <
    MAYOR >
    MAYOR O IGUAL >=
    MENOR O IGUAL <=
    
    CASOS ESPECIALES
    BETWEEN A AND B : ENTRE A Y B
    IN: EN
    ISNULL(): ES NULO
    IS NOT NULL: NO ES NULO
    LIKE: COMO
    NOT LIKE: NO COMO

    OPERADORES LOGICOS
    OR: O
    AND: Y
    NO: NO
    
    COMODINES PARA LIKE
    % CUALQUIER CANTIDAD DE CARACTERES
    _ UN CARACTER DESCONOCIDO
    USAMOS LIMIT PARA LIMITAR EL NUMERO EN LA CONSULTA
*/
# 1. NOMBRE Y APELLIDIOS QUE SE REGISTRARON EN 2024
SELECT NOMBRE,APELLIDOS FROM USUARIOS WHERE YEAR(FECHA) = '2024';

# 2. NOMBRE Y APELLIDIOS QUE NO SE REGISTRARON EN 2020 O FECHA NULA
SELECT NOMBRE,APELLIDOS FROM USUARIOS WHERE YEAR(FECHA) != '2024' OR ISNULL(FECHA);

# 3. MOSTRAR EL EMAIL DE LOS USUARIOS CUYO APELLIDOS CONTENGAN LA LETRA A 
# Y QUE LA CONTRASEÑA SEA pruebapass

SELECT EMAIL FROM USUARIOS WHERE APELLIDOS LIKE '%i%' AND PASSWORD = 'pruebapass';
# 4. LIMIT
SELECT * FROM USUARIOS LIMIT 3; # SOLO NOS DARA LOS 3 PRIMEROS DE LA LISTA
# 5. MIN MAX, VALOR MAXIMO Y MINIMO
SELECT MAX(ID) FROM USUARIOS;