/* 
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Other/SQLTemplate.sql to edit this template
 */
/**
 * Author:  hchri
 * Created: 28 feb 2024
 */

/*
    PRIMERO CREAMOS LAS TABLAS QUE NO TIENE RELACION
    ENGINE=InnoDB NOS PERMITE TENER CLAVES FORANEAS, INTEGREDAD REFERENCIALY MEJORAR RENDIMIENTO
    ENGINE=MyISAM MAYOR VELOCIDAD,APLICACIONES PARA MUCHISIMAS SELECT , NO RESPETA LA INTEGREDAD 
    REFERENCIAL
*/
CREATE TABLE USUARIOS(
    ID INT(255) AUTO_INCREMENT NOT NULL,
    NOMBRE VARCHAR(100) NOT NULL,
    APELLIDOS VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    FECHA DATE NOT NULL,
    CONSTRAINT PK_USUARIOS PRIMARY KEY(ID),
    CONSTRAINT EMAIL UNIQUE(EMAIL)
)ENGINE=InnoDb;
CREATE TABLE CATEGORIAS(
    ID INT(255) AUTO_INCREMENT NOT NULL,
    NOMBRE VARCHAR(100) NOT NULL,
    CONSTRAINT PK_CATEGORIAS PRIMARY KEY(ID)
)ENGINE=InnoDb;
/*
    CREAMOS LA TABLA QUE TIENE RELACIONES
    VEMOS COMO SE HACE UNA TABLA CON RELACIONES O CON CLAVES FORANEAS
*/
CREATE TABLE ENTRADAS(
    ID INT(255) AUTO_INCREMENT NOT NULL,
    USUARIO_ID INT(255) NOT NULL,
    CATEGORIA_ID INT(255) NOT NULL,
    TITULO VARCHAR(255) NOT NULL,
    DESCRIPCION MEDIUMTEXT,
    FECHA DATE NOT NULL,
    CONSTRAINT PK_ENTRADA PRIMARY KEY(ID),
    CONSTRAINT FK_ENTRADA_USUARIO FOREIGN KEY(USUARIO_ID) REFERENCES USUARIOS(ID),
    CONSTRAINT FK_ENTRADA_CATEGORIA FOREIGN KEY(CATEGORIA_ID) REFERENCES CATEGORIAS(ID)
)ENGINE=InnoDb;

/* CASCADE
    ON DELETE CASCADE : SIGNIFICA QUE SI SE BORRA EL REGISTRO TAMBIEN SE BORRA EL REGISTRO AL QUE ESTA UNIDO
    ON UPDATE CASCADE : IGUAL PERO ACTUALIZA
    ON DELETE NULL : QUE SI SE BORRA EL REGISTRO EL OTRO SE PONGA EN NULL
    ON DELETE DEFAULT : QUE SI SE BORRA EL REGISTRO EL OTRO SE PONGA EN DEFAULT
    ON DELETE NO ACTION : ESTA POR DEFECTO, QUE SI SE BORRA NO HAGA NADA
*/
