/* 
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Other/SQLTemplate.sql to edit this template
 */
/**
 * Author:  hchri
 * Created: 1 mar 2024
 */
# INSERTS PARA CATEGORIAS
    INSERT INTO CATEGORIAS VALUE(NULL,'ACCION');
    INSERT INTO CATEGORIAS VALUE(NULL,'ROL');
    INSERT INTO CATEGORIAS VALUE(NULL,'DEPORTES');
# INSERTS PARA ENTRADAS
    INSERT INTO ENTRADAS VALUES(NULL,1,1,'GTA 5','REVIEW DEL GTA 5',CURDATE());
    INSERT INTO ENTRADAS VALUES(NULL,1,2,'LOL','REVIEW DEL LOL',CURDATE());
    INSERT INTO ENTRADAS VALUES(NULL,1,3,'DBTK','DRAGON BALL TENKAICHI',CURDATE());

    INSERT INTO ENTRADAS VALUES(NULL,2,1,'ASSASINS ONLINE','REVIEW DEL ASSAINS',CURDATE());
    INSERT INTO ENTRADAS VALUES(NULL,2,2,'WOW','REVIEW DEL WOW',CURDATE());
    INSERT INTO ENTRADAS VALUES(NULL,2,3,'PES19','REVIEW PES 19',CURDATE());

    INSERT INTO ENTRADAS VALUES(NULL,3,1,'COD ONLINES','REVIEW DEL COD',CURDATE());
    INSERT INTO ENTRADAS VALUES(NULL,3,2,'FORNITE','REVIEW DEL FORNITE',CURDATE());
    INSERT INTO ENTRADAS VALUES(NULL,3,3,'FORMULA 1','FORMULA 1',CURDATE());

# CONSULTAS DE AGRUPAMIENTO
# AQUI AGRUPA POR CATEGORIAS Y MUESTRA SOLA LA 1 DE CADA CATEGORIA
# SOBRE TODO SIRVE PARA VER CANTIDAD DE ALGO SUELE IR CON EL ATRIBUTO COUNT
SELECT COUNT(TITULO) AS 'NUMERO DE ENTRADAS', CATEGORIA_ID FROM ENTRADAS GROUP BY CATEGORIA_ID;

# AQUI EL CONDICIONAMIENTO NO SE HACE CON WHERE SI NO CON HAVING
SELECT COUNT(TITULO) AS 'NUMERO DE ENTRADAS', CATEGORIA_ID FROM ENTRADAS GROUP BY CATEGORIA_ID
HAVING COUNT(TITULO) >= 2;

# FUNCIONES DE AGRUPAMIENTO
/*
AVG PERMITE SACAR LA MEDIA
COUNT CUENTA EL NUMERO DEL RESULTADO
    -- SELECT COUNT(AGE) FROM USUARIOS; CUENTA 4 DE 6, YA QUE SOLO TIENE EN CUENTA QUE EL CAMPO AGE NO ESTE VACIO
    -- POR ELLO CUENTA EL NUMERO DE RESULTADOS DE LA CONSULTA
MAX VALOR MAXIMO DEL GRUPOI
MIN VALOR MIN DEL GRUPO
SUM SUMAR TODO EL CONTENIDO DEL GRUPO
*/
# SUMA ID POR ID Y LUEGO LAS DIVIDE ENTRE EL NUMERO 1+2+3+4/4 EJEMPLO
SELECT AVG(ID) AS 'MEDIA DE ENTRADAS' FROM ENTRADAS;

# MAX
SELECT MAX(ID) AS 'MAXIMO ID', TITULO FROM ENTRADAS;
# TANTO LA MIN COMO LA MAX ESTAN MAL HECHAS LAS CONSULTAS, EN TITULO SIEMPRE TE VA A
# SALIR LA PRIMERA OJOOO.
# MIN
SELECT MIN(ID) AS 'MAXIMO ID', TITULO FROM ENTRADAS;

SELECT SUM(ID) AS 'SUMA ID' FROM ENTRADAS;


