/* 
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Other/SQLTemplate.sql to edit this template
 */
/**
 * Author:  hchri
 * Created: 29 feb 2024
 */
# 1-INSERTAR NUEVOS REGISTROS

INSERT INTO usuarios VALUE(
    null,
    "Andres",
    "Herrera",
    "hchristianandres@gmail.com",
    "pruebapass",
    "2024-02-29" # FORMATO AMERICANO
);
INSERT INTO usuarios VALUE(null,"Christian","Andrade","aa@gmail.com","pruebapass","2024-02-29");
INSERT INTO usuarios VALUE(null,"Jorge","Andrade","bb@gmail.com","pruebapass","2024-02-29");
INSERT INTO usuarios VALUE(null,"Mari","Jima","mari@gmail.com","pruebapass","2024-02-29");

SELECT * FROM usuarios; # Muestra todos los campos de usuario

# INSERTAR FILA CON CIERTAS COLUMNAS, SIEMPRE Y CUANDO NO SEAN NULL
INSERT INTO usuarios(email,password) VALUE ("ADMIN@ADMIN.COM","ADMIN");
# --------------------------------------------------------------------------------------
# 2-SELECCIONAR INFORMACIÓN
# MOSTRAR SOLO REGISTRO QUE QUEREMOS OJO CUIDADO EL ORDEN EN QUE QUEREMOS QUE NOS LO MUESTRE
SELECT * FROM USUARIOS;
SELECT EMAIL,NOMBRE,PASSWORD FROM USUARIOS;
# --------------------------------------------------------------------------------------
# 3-OPERADORES ARITMETICOS
# CURIOSO, TE SALE EN TODAS LAS FILAS LA SUMA
SELECT EMAIL, (4 + 7) FROM USUARIOS;

# PODEMOS PONER ALIAS
SELECT EMAIL, (4 + 7) AS 'OPERACION' FROM USUARIOS;

# PODEMOS SACAR INFORMACION POR ORDEN
# PUEDE SER DESCENDENTE O ASCENDENTE
SELECT ID,NOMBRE,EMAIL, (4 + 7) AS 'OPERACION' FROM USUARIOS ORDER BY ID;
SELECT ID,NOMBRE,EMAIL, (4 + 7) AS 'OPERACION' FROM USUARIOS ORDER BY ID DESC;
SELECT ID,NOMBRE,EMAIL, (4 + 7) AS 'OPERACION' FROM USUARIOS ORDER BY ID ASC;

# PODEMOS HACER OPERACIONS USANDO LAS COLUMNAS
SELECT ID,NOMBRE,EMAIL, (ID + 7) AS 'OPERACION' FROM USUARIOS ORDER BY ID;
# OJO PODEMOS HACER LA CONSULTA INVOCANDO AL ALIAS 
SELECT ID,NOMBRE,EMAIL, (ID + 7) AS 'OPERACION' FROM USUARIOS ORDER BY OPERACION;
# --------------------------------------------------------------------------------------
# 4-FUNCIONES MATEMATICAS QUE PODEMOS HACER
/*
    SUM(), SUMA ELEMENTOS DE UN COLUMNA
    ABS()N.ABSOLUTO
    CEIL()REDONDEO
    FLOOR()REDONDEO A LA BAJA
    RAND() NUMERO ALEATORIO
    BUSCAR SQL FUNCTIONS MATH Y TE SALEN LAS QUE HAY
    ROUND(7.765,2) TE SACA EL NUMERO CON LOS DECIMALES QUE LE DIGAS
    TRUNCATE(7.765,2)QUITAR DECIMALES, PARECIDO A ROUND
    AVG(), TE DA LA MEDIA DE LOS ELEMENTOS DE UNA COLUMNA
*/
SELECT ID,NOMBRE,EMAIL, (ID + RAND()) AS 'OPERACION' FROM USUARIOS ORDER BY OPERACION ASC;
# --------------------------------------------------------------------------------------
# 5-FUNCIONES DE CARACTERES
# CONVERTIR CARACTERES EN MAYUSCULA
/*
    UPPER(NOMBRE)
    LOWER(APELLIDOS)
    CONCAT(NOMBRE, ' ',APELLIDOS)
*/
SELECT CONCAT(NOMBRE,' ',APELLIDOS) AS 'NOMBRE_COMPLETO' FROM USUARIOS ORDER BY EMAIL DESC;

# PODEMOS COLOCAR FUNCIONES DENTRO DE OTRAS
SELECT UPPER(CONCAT(NOMBRE,' ',APELLIDOS)) AS 'NOMBRE_COMPLETO' FROM USUARIOS ORDER BY EMAIL DESC;

# FUNCION LENGTH, NUMERO DE CARACTERES DE UN TEXTO OJO CUENTA EL ESPACIO TAMBIEN
SELECT CONCAT(NOMBRE,' ',APELLIDOS) AS 'NOMBRE_COMPLETO', LENGTH(CONCAT(NOMBRE,' ',APELLIDOS)) AS 'LONGITUD_NOMBRE' FROM USUARIOS ORDER BY EMAIL DESC;

# FUNCION TRIM QUITA LOS ESPACIOS
# --------------------------------------------------------------------------------------
# 6-FUNCIONES DE FECHA
# CURDATE() TE MUESTRA LA FECHA ACTUAL
SELECT NOMBRE, FECHA, CURDATE() AS 'FECHA_ACTUAL' FROM USUARIOS ORDER BY ID DESC;

# DIFERENCIA DE FECHAS DATEDIFF, TE DICE LOS DIAS QUE HAY DE DIFERENCIA
SELECT NOMBRE, FECHA, DATEDIFF(FECHA,CURDATE()) AS 'DIFERENCIA_FECHA' FROM USUARIOS ORDER BY ID DESC;
/* 
    DAYNAME(FECHA) SACA EL NOMBRE DEL DIA
    DAYMONTH(FECHA) NOMBRE DEL MES
    DAYOFWEEK(FECHA) NUM DE LA SEMANA 1-7
    DAYOFYEAR(FECHA) DIA DEL AÑO
    MONTH(FECHA) NUMERO DEL MES
    YEAR(FECHA) AÑO
    HOUR/MINUTE/SECOND(FECHA) QUE PODEMOS SACAR
    SYSDATE() HORA Y FECHA DEL ORDENADOR
*/
# CURTIME SACA LA HORA EN LA QUE ESTAMOS

SELECT NOMBRE, CURTIME() AS 'HORA' FROM USUARIOS ORDER BY ID;

# FORMATEAR FECHA DATE_FORMAT(FECHA,'%d-%m-%y')

SELECT NOMBRE,DATE_FORMAT(FECHA,'%d-%m-%y') AS 'FECHA EUROPEA' FROM USUARIOS ORDER BY ID;
# --------------------------------------------------------------------------------------
# 7-FUNCIONES GENERALES

# COMPROBAR SI ALGO ES NULO LO HACE CON 0 Y 1 ISNULL(),1 TRUE Y 0 FALSE
SELECT NOMBRE, ISNULL(APELLIDOS) AS 'NULO' FROM USUARIOS;
# IFNULL(), TE SACA LA INFORMACION DEL CAMPO Y SI ES NULL TE PONE ALGO
SELECT NOMBRE, IFNULL(APELLIDOS,'CAMPO_VACIO') AS 'CAMPO_VACIO' FROM USUARIOS;
# COMPROBAR SI DOS DATOS SON IGUALES, STRCMP(NOMBRE,APELLIDOS)
SELECT NOMBRE, STRCMP('HOLA','HOLA') AS 'IGUAL' FROM USUARIOS;

# CURIOSO SABER LA VERSION DE MYSQL A TRAVES DE UNA CONSULTA
SELECT VERSION() AS 'VERSION_SQL' FROM USUARIOS; # SACA EL NUMERO DE FILAS
# --------------------------------------------------------------------------------------
# DISCTINCT, SI HAY DATOS QUE SE REPITEN ESTE SOLO SACA AQUELLOS QUE NO
SELECT DISTINCT VERSION() AS 'VERSION_SQL' FROM USUARIOS;# SOLO SACA 1
#
# --------------------------------------------------------------------------------------
# IN, COMPRUBA QUE SEA IGUAL A LO PEDIDO
SELECT * FROM USUARIOS WHERE NAME IN ('ANDRES','CARLOS'); 