/* 
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Other/SQLTemplate.sql to edit this template
 */
/**
 * Author:  hchri
 * Created: 5 mar 2024

 CONSULTAS MULTITABLA
 */
# MOSTRAR LAS ENTRAS CON EL NOMBRE DEL AUTOR Y EL NOMBRE DE LA CATEGORIA
SELECT ENTRADAS.TITULO, USUARIOS.NOMBRE, CATEGORIAS.NOMBRE
FROM ENTRADAS, USUARIOS,CATEGORIAS; # CONSULTA A TODAS LAS TABLAS Y SACA LA INFORMACION REPETIVA

# PODEMOS PONER ALIAS A LAS TABLAS PARA QUE NO SE HAGA MUY LARGA LA CONSULTA
SELECT E.TITULO, U.NOMBRE, C.NOMBRE
FROM ENTRADAS E, USUARIOS U,CATEGORIAS C;

# PARA QUE NO SE REPITA LA INFORMACCION Y SOLO SACAR LA INFORMACIÓN QUE QUEREMOS

SELECT E.ID,E.TITULO, U.NOMBRE, C.NOMBRE
FROM ENTRADAS E, USUARIOS U,CATEGORIAS C
WHERE E.USUARIO_ID = U.ID AND E.CATEGORIA = C.ID;

# MOSTRAR EL NOMBRE DE LAS CATEGORIAS Y AL LADO CUANTAS ENTRADAS TIENEN
SELECT CATEGORIAS.NOMBRE, COUNT(ENTRADAS.ID)
FROM CATEGORIAS,ENTRADAS
WHERE ENTRADAS.CATEGORIAS_ID = CATEGORIAS.ID
GROUP BY ENTRADAS.CATEGORIA_ID; 
# MOSTRAR EL EMAIL DE USUARIOS Y AL LADO CUANTAS ENTRADAS TIENEN
SELECT USUARIOS.EMAIL, COUNT(TITULO)
FROM USUARIOS,ENTRADAS
WHERE ENTRADAS.USUARIOS_ID = USUARIOS.ID
GROUP BY ENTRADAS.USUARIOS_ID; 

# ESTA FORMA NO ES LA MAS OPTIMA DE HACERLO ESTA BIEN PERO RECORREO TODAS LAS TABLAS
# Y ES PESADO PARA EL SISTEMA
# ----------------------------------------------------------------------------------
# INNER JOIN, ESTA MAS OPTIMIZADO
# SE LEE MEZCLA LA TABLA ENTRADA CON USUARIOS/CATEGORIAS SOLO CUANDO LA CONDICION

SELECT ENTRADAS.TITULO, USUARIOS.NOMBRE, CATEGORIAS.NOMBRE
FROM ENTRADAS
INNER JOIN USUARIOS ON ENTRADA.USUARIOS_ID = USUARIOS.ID
INNER JOIN CATEGORIAS ON ENTRADA.CATEGORIAS_ID = CATEGORIAS_ID;

# ------------------------------------------------------------------------------------
SELECT COTAGORIAS.NOMBRE, COUNT(ENTRADA.ID)
FROM CATEGORIAS # TE MUESTRA SI HAY ALGO 0 O NULL, CON INNER NO LO HACE
LEFT JOIN ENTRADAS ON ENTRADA.CATEGORIA_ID = CATEGORIA.ID # MANTIENE TODAS LAS FILAS DE LA IZQUIERDA
GROUP BY ENTRADA.CATEGORIA_ID;

# ------------------------------------------------------------------------------------
SELECT COTAGORIAS.NOMBRE, COUNT(ENTRADA.ID)
FROM ENTRADAS # TE MUESTRA SI HAY ALGO 0 O NULL, CON INNER NO LO HACE
RIGHT JOIN CATEGORIAS ON ENTRADA.CATEGORIA_ID = CATEGORIA.ID # MANTIENE TODAS LAS FILAS DE LA DERECHA
GROUP BY ENTRADA.CATEGORIA_ID;

