
/**
 * Author:  hchri
 * Created: 27 feb 2024
 */
/*
CREAR UNA TABLA con sus tipos de DATOS:
-----------------------------------------------------------
NUMERICOS: DOS GRUPOS, LOS QUE ESTAN EN COMO FLOTANTE(DECIMALES)Y LOS QUE NO
1.  TINYINT:VA DESDE -128 A 127, SIN SIGNO DESDE 0 A 255
2.  BIT O BOOL: 0 Ó 1 
3.  SMALLINT: DESDE 0 A 65535
4.  MEDIUMINT: DESDE 0 A 16777215
5.  INTEGER,INT: DESDE 0 A 429.4967.295
6.  BIGINT: DESDE 0 A 18......
7.  FLOAT(M,D):M TOTAL DE DIGITOS Y D ES EL NUM DE DECIMALES
8.  REAL,DOUBLE(M,D):PRESICION DOBLE
9.  DECIMAL,DEC,NUMERIC(M,D): ALMACENA COMO UNA CADENA, UN CARACTER PARA CADA 
    DIGITO DE VALOR.
-----------------------------------------------------------
FECHA: MYSQL NO COMPRUEBA DE MANERA ESTRICTA SI UNA FECHA ES VALIDA O NO,
COMPRUEBA EL MES (0-12) Y DIA (0-31)
1.  DATE: DEL 1 DE ENERO DE 1001 AL 31 DE DICIEMBRE DE 9999(Y-M-D)
2.  DATETIME: COMBINA FECHA Y HORA(Y-M-D H:M:S)
3.  TIMESTAMP: COMBINA FECHA Y HORA DESDE 1 DE ENERO DE 1970 00:00:00 HASTA 19 DE ENERO DE 2038
    FORMATO DE ALMACENAMIENTO DEPENDE DEL TAMAÑO DEL CAMPO
4.  TIME:ALMACENA HORA H:M:S
5.  YEAR:DESDE 1901 HASTA 2155
-----------------------------------------------------------
CADENA
1.  CHAR: DESDE 0 A 255 CARACTERES, LONGITUD FIJA
2.  VARCHAR: DESDE 0 A 255 CARACTERES, LONGITUD VARIABLE
3.  BLOB Y TEXT:DESDE 0 A 65535 CARACTERES
4.  MEDIUMBLOB Y MEDIUMTEXT: HASTA 16.777.215 CARACTERES
5.  LONGBLOB Y LONGTEXT: HASTA 4G

*/
/*CREAR TABLA, LO QUE HACEMOS ES ESCRIBIRLA AQUI Y COPIARLA EN EL COMPILADOR*/
CREATE TABLE usuarios(
    id int(11),
    nombre varchar(100),
    apellidos varchar(255),
    email   varchar(100),
    password varchar(255)
);
/*RESTRICCIONES DE INTEGRIDAD*/
/*
NOT NULL NO PUEDE IR VACIA
NULL PUEDE IR VACIA
DEFAULT '' POR DEFECTO UN VALOR
AUTO_INCREMENT SOLO EN LAS PK DE LA TABLA ESTE CASO ID
PRIMARY KEY SE DEFINE EN LAS CONSTRAINT
*/
CREATE TABLE usuarios(
    id int(11) AUTO_INCREMENT NOT NULL,
    nombre varchar(100) NOT NULL,
    apellidos varchar(255)DEFAULT'HERRERA',
    email   varchar(100)NOT NULL,
    password varchar(255),
    CONSTRAINT PK_USUARIOS PRIMARY KEY(ID)
);
/*RENOMBRAR TABLAS*/
ALTER TABLE usuarios RENAME TO usuarios_renom;

# CAMBIAR EL NOMBRE DE UNA COLUMNA
ALTER TABLE usuarios_renom CHANGE
apellidos
apellido VARCHAR(100) NOT NULL; 

# MODIFICAR COLUMNA SIN CAMBIAR NOMBRE
ALTER TABLE usuarios_renom MODIFY apellido VARCHAR(200) NOT NULL;

# AÑADIR COLUMNA
ALTER TABLE USUARIOS_RENOM ADD WEBSITE VARCHAR(200) NULL;

# AÑADIR RESTRICCION A UNA COLUMNA
/*
USAMOS UNIQUE, PARA RESTRICCION DE VALOR UNICO
*/
ALTER TABLE USUARIOS_RENOM ADD CONSTRAINT uq_email UNIQUE(email);

# BORRAR UNA TABLA
ALTER TABLE usuarios_renom DROP website;

# DISEÑO DE TABLAS CON EL PROGRAMA DIA

